### ISSUE TITLE
Investigate apparent expediter issue

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef_secrets#64]
Investigate apparent expediter issue.

A chef_secrets:master verify test on a recently-opened PR failed.  A cursory glance seemed to indicate an issue with expediter.  I was told other failures have been observed as well, which seems to indicate that the problem is not with the sample PR provided.

### PR:
https://github.com/chef/chef_secrets/pull/62

### Failed verify test:
https://buildkite.com/chef-oss/chef-chef-secrets-master-verify/builds/43#40260a3b-6abb-4ef7-89d8-26f1e04bdc74

### Replication Case
Run a master verify build on the sample PR provided.

**Comment by PrajaktaPurohit** [comment]
closing - does not look like we have this issue anymore.
